// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc1pNPptOWyL1B9dUkl5OEi-yww5_lDvU',
    appId: '1:12850028492:android:d5a804de0fa99687520769',
    messagingSenderId: '12850028492',
    projectId: 'tourismtodorecommender',
    storageBucket: 'tourismtodorecommender.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJc2zq009lL-HPHDiWdsKoo13RTBu0Jjw',
    appId: '1:12850028492:ios:cf39cdc680dcda30520769',
    messagingSenderId: '12850028492',
    projectId: 'tourismtodorecommender',
    storageBucket: 'tourismtodorecommender.appspot.com',
    iosClientId: '12850028492-mgq4g9oe5nnlnadi5dio2th3r4nbd4lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
